# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Onward Survey CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  format:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Run formatting check
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier: true

  client:
    name: Web Client - Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        working-directory: ./src/client
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./src/client
        run: yarn test

  server:
    name: Server - Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        working-directory: ./src
        run: yarn install --frozen-lockfile

      - name: Get changed files
        id: get_changed_files
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true

      - name: Run ESLint
        # Get all changed files, filter to only .js, .ts, .tsx, and lint them
        run: yarn ci-lint `echo ${{ steps.get_changed_files.outputs.files }} | tr " " "\n" | grep ".js$\|.ts$\|.tsx" | tr "\n" " "`

      - name: Compile TypeScript
        working-directory: ./src
        run: yarn build
